### ISSUE TITLE
More process information

### ISSUE THREAD

**Issue by dirkniemeier** [eolwral/OSMonitor#55]
Hi,
I have problems with an process mmcqd/0 on my S3. It is creating a lot of cpu usage. Is it possible to get some more information about that process. Which storage device cause that, or a special file write. It would be helpful to locate the problem.

TIA
  Dirk

**Comment by eolwral** [comment]
Hello Dirk,

"mmcqd is a kernel thread, responsible for managing queued I/O operations on the SD card. A high CPU usage from that process indicates that you have a disk I/O bottleneck."
> http://raspberrypi.stackexchange.com/questions/7394/what-is-the-mmcqd-process

If you have tried to use some tools like "iotop", you will discover it doesn't work, because some system features are not supported by Android, it is hard to indicate single process which consumes a lot of I/O.    

Because "mmcqd" is a system process, I think you may check dmesg that you can find on message tab, Android's logcat isn't useful, but I afraid those messages may not help you at all, some system processes never output log.
 
P.S. I suspect it may cause by damaged sdcard, because I had same issue with my previous phone, you may check sdcard on another device, 

Thanks!

**Comment by eolwral** [comment]
Closed, if problem can't solve, please re-open again.
